#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if ! ./node_modules/.bin/lint-staged; then
  echo 'Please fix the linter issues and run'
  echo '    npm run lint'
  echo 'to verify your changes.'
  echo ''
  exit 1
fi
